[package]
name = "ghastly-macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
convert_case = "0.7.1"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
